POST http://localhost:8080/springmvc_war_exploded/user/quick14
Content-Type: application/json

[
  {
    "username": "hum",
    "age": 18
  },
  {
    "username": "tan",
    "age": 20
  }
]

###
POST http://localhost:8080/springmvc_war_exploded/user/quick13
Content-Type: application/x-www-form-urlencoded

userList[0].username=谭勇祥&userList[0].age=18&userList[1].username=tan&userList[1].age=20

###
